name: App Build
on:
  push:
    branches:
      - dev
    paths:
      - "**"
  pull_request:
    paths:
      - "**"
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: docker build -t learnhouse .
        working-directory: .
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: learnhouse/images
          event-type: build-images
          client-payload: |
            {
              "ref": "${{ github.sha }}",
              "branch": "${{ github.head_ref || github.ref_name }}"
            }
